name: MySQL Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: todo_app_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -hmysql -uroot -prootpassword; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Setup database schema (if needed)
        run: |
          mysql -h mysql -u root -prootpassword -e "CREATE DATABASE IF NOT EXISTS todo_app_test;"

      - name: Run tests
        env:
          DB_HOST: mysql
          DB_USER: root
          DB_PASSWORD: rootpassword
          DB_DATABASE: todo_app_test
        run: |
          # Führe deine Tests aus, die die MySQL-Datenbank verwenden
          echo "Running MySQL tests..."
          # Hier kannst du deine Tests ausführen, z.B. mit npm
          # Beispiel: npm test
